package com.auliaridhov.moviecatalog.ui.utils;

import com.auliaridhov.moviecatalog.data.source.remote.response.ResultsItem;
import java.util.ArrayList;
import java.util.List;

public class FakeDataDummy {
    public static List<ResultsItem> generateDummyMovies() {
        ArrayList<ResultsItem> movies = new ArrayList<>();
        List<Integer> genreIds = new ArrayList<Integer>();
        genreIds.add(21);
        genreIds.add(32);
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        return movies;
    }

    public static List<ResultsItem> generateDummyTvShow() {
        ArrayList<ResultsItem> movies = new ArrayList<>();
        List<Integer> genreIds = new ArrayList<Integer>();
        genreIds.add(21);
        genreIds.add(32);
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        return movies;
    }
}
