package com.auliaridhov.moviecatalog.ui.utils;

import com.auliaridhov.moviecatalog.data.MoviesEntity;
import com.auliaridhov.moviecatalog.data.source.remote.response.ResultsItem;

import java.util.ArrayList;
import java.util.List;

public class FakeDataDummy {
    public static List<ResultsItem> generateDummyMovies() {
        ArrayList<ResultsItem> movies = new ArrayList<>();
        List<Integer> genreIds = new ArrayList<Integer>();
        genreIds.add(21);
        genreIds.add(32);
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        movies.add(new ResultsItem("John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                "en",
                "Greenland",
                false,
                "Greenland",
                genreIds,
                "/sA154deR0X51EcR2lm2FfDczryg.jpg",
                "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
                "2020-07-29",
                "movie",
                7.1,
                338.37,
                524047,
                false,
                456,
                "Greenland"));
        return movies;
    }

    public static List<MoviesEntity> generateDummyTvShow() {
        ArrayList<MoviesEntity> tvShow = new ArrayList<>();
        tvShow.add(new MoviesEntity("152",
                "https://image.tmdb.org/t/p/w500/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
                "Marvel's Agents of S.H.I.E.L.D.: Slingshot",
                "Agent Phil Coulson of S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) puts together a team of agents to investigate the new, the strange and the unknown around the globe, protecting the ordinary from the extraordinary.",
                "125.134",
                "2013-09-24"));
        tvShow.add(new MoviesEntity("412",
                "https://image.tmdb.org/t/p/w500/3EDyt08lgg26WhW7nQE4r7YL3ul.jpg",
                "WWF Wrestling Challenge",
                "WWF Wrestling Challenge was a professional wrestling television program produced by the World Wrestling Federation. It was syndicated weekly and aired from 1986 to 1995. The show became simply known as WWF Challenge in 1995. The show featured matches, pre-match interviews, and occasionally, summarized weekly events in WWF programming. Matches primarily saw top tier and mid-level talent versus jobbers. At times, there was a \\\"feature\\\" match between main WWF talent. As with other syndicated WWF programming, the show promoted WWF event dates and house shows in local media markets.",
                "4.151",
                "1986-09-07"));
        tvShow.add(new MoviesEntity("32542",
                "https://image.tmdb.org/t/p/w500/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg",
                "The Good Doctor",
                "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives?",
                "695.587",
                "2017-09-25"));
        tvShow.add(new MoviesEntity("3636",
                "https://image.tmdb.org/t/p/w500/rFdzPaFdfm3LZ9lBYtiM08MT0n1.jpg",
                "Hey Arnold!",
                "The daily life of Arnold--a fourth-grader with a wild imagination, street smarts and a head shaped like a football.",
                "30.554",
                "1996-10-07"));
        tvShow.add(new MoviesEntity("373",
                "https://image.tmdb.org/t/p/w500/xpm5ypAg0FySsHVW0smOTgQbhF.jpg",
                "Cat vs. Dog",
                "Pets fighting like cats and dogs, unable to live under the same roof, can tear otherwise peaceful homes into turbulent messes. Enter cat behaviorist Jackson Galaxy and dog trainer Zoe Sandor, who assist families seeking peace between ill-behaved kitties and pooches. After meeting with families, Jackson and Zoe address the behaviors of both humans and animals, then they create long-term plans featuring daily routines and procedures, with the goal of conflict resolution to create homes where cats and dogs can coexist.",
                "0.6",
                "2017-11-11"));
        return tvShow;
    }
}
